database_uri: postgresql://postgres:postgres@localhost:5432/gitops
celery_broker_url: redis://localhost:6379/0
celery_result_backend: redis://localhost:6379/0
argocd:
  url: http://argocd.example.com
  api_token: "${ARGOCD_TOKEN}"
